<a href="https://colab.research.google.com/github/surya2347/Study_Data-Analysis/blob/main/2%EC%9D%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
st1 = "123"
st2 = "OneTwoThree"
# 숫자만로 이루어져있는지 확인
print(st1.isdigit())   # 문자열로 이루어진 숫자여도 ok, 그냥 정수 숫자여도 ok
print(st2.isdigit())
# 문자로만 이루어져있는지 확인
print(st1.isalpha())
print(st2.isalpha())

str.startswith("abc")   # str이 "abc로 시작하는지 확인하는 메서드" True/Flase


True
False
False
True


In [14]:
pnum = input("전화번호 입력 : ")
# '-'을 넣었을 시 하이픈 삭제
if '-' in pnum:
  while '-' in pnum:
    pnum = pnum.replace('-', "")

if pnum.isdigit() and pnum.startswith('010') and len(pnum) == 11:
  print("전화번호가 입력되었습니다")
else:
  print("정상적이지 않은 전화번호입니다.")

# and    &
# or     |
# not    ~

전화번호 입력 : 010-7654-4568
전화번호가 입력되었습니다


In [12]:
# 조건문 in, not in
s = "Tomato spaghetti"

if s.find('ghe') != -1:
  print('있습니다')
else:
  print("없습니다.")

if 'ghe' in s:
  print('있습니다')
else:
  print("없습니다.")


있습니다


In [22]:
# 반복문 : while
cnt = 0
while cnt < 3:
  print(cnt, end =' ')
  cnt += 1
print()

# 반복문 : break
i = 0
while i < 100:
  print(i, end=' ')
  i += 1
  if i == 20:
    break
print()

# 반복문 : continue
for i in range(1,11):
  if i % 2 == 0:
    continue
  print(i,end = ' ')
print()

# 이중 for 루프
for i in [1,2]:
  for j in ['a','b','c']:
    print(i*j, end = ' ')
print()

sr = ['father', 'mother', 'brother']
cnt = 0
for s in sr:
  print(s, end = "#")
  for c in s:
    print(c, end=' ')
    cnt += 1
print(cnt)


0 1 2 
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 
1 3 5 7 9 
a b c aa bb cc 
father#f a t h e r mother#m o t h e r brother#b r o t h e r 19


In [30]:
# 튜플
frns = ['동수', 131120,'진우', 130312,'선영', 13904]
frn = ("동수", 131120)
print(frn[0])
#frn[0] = '진우'  # 튜플은 값이 치환되지 않음

frns = [('동수', 131120),('진우', 130312),('선영', 13904)]


# 딕셔너리
dc = {"정은호":"010-4568-4465","구아나":"010-9352-0035"}  # 키:값 의 형태
print(dc)
print(dc["정은호"])


# in, not in 연산을 통해 존재 유무를 확인하는 대상은"값"이 아니라 "키"
dc1 = {'코카콜라':900, '삼다수':450}
if '삼다수' in dc1:
  dc1['삼다수'] = 500
print(dc1)

if '카페라떼' not in dc1:
  dc1['카페라떼'] = 1200  # 딕셔너리 추가하는 법
print(dc1)



동수
{'정은호': '010-4568-4465', '구아나': '010-9352-0035'}
010-4568-4465
{'코카콜라': 900, '삼다수': 500}
{'코카콜라': 900, '삼다수': 500, '카페라떼': 1200}


In [31]:
# 많이 쓰이는 4가지 라이브러리
# numpy
# pandas
# matplotlib
# sk-learn

In [52]:
# numpy (Numerical Python)
'''
# vector(배열): 같은 데이터 형의 값들을 나열
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array(['apple','banana','orange'])
c = np.array([True, False, True, True])

print("Numeric Vector: ", a)
print("String Vector: ", b)
print("Boolean Vector: ", c)

# 빈배열 생성
x = np.empty(3)
print('빈 배열 생성하기: ',x)

y = np.zeros(3)
print('0으로 초기화 된 배열 생성하기 : ',y)

# 배열 채우기
x[0] = 3
x[1] = 5
x[2] = 3
print(x)

# np.arange()
arr1 = np.arange(10)  # range의 값들을 numpy의 arr로 생성하는 것
print(arr1)

arr2 = np.array(0)
print(arr2)
'''
# np.repeat() 함수
repeated_vals = np.repeat(8,4)  # 반복할 값, 반복횟수
print(repeated_vals)

repeated_arr = np.repeat([1,2,4],2)  # 배열을 반복할 경우 각 배열의 값들을 반복한다.
print(repeated_arr)

repeated_each = np.repeat([1,2,4], repeats = [1,2,3])  # 각 배열의 값들을 repeats로 준 배열의 값 만큼 각각 반복한다.
print(repeated_each)

# np.tile()함수
repeat_whole = np.tile([1,2,4], 2)       # 배열 전체를 2번 반복한다.
print(repeat_whole)

# 벡터의 길이
a = np.array([1,2,3,4,5])
print(len(a))
print(a.shape)    # shape 속성은 배열의 각 차원을 튜플 형태로 반환
print(a.size)     # size 속성은 전체 요소 수 구하기

# Numpy 벡터 슬라이싱(slicing)
np.random.seed(42)
a = np.random.randint(1,21,10)  # 1부터 21까지 랜덤 int 10개
print(a)
print(a[1])
print(a[2:5])  # slicing: 세 번째부터 다섯번째 값 까지
print(a[-3::-1])  # 캬캬캬 야무지다!  이럴거면 반대로 정렬해서 쓰세요


[8 8 8 8]
[1 1 2 2 4 4]
[1 2 2 4 4 4]
[1 2 4 1 2 4]
5
(5,)
5
[ 7 20 15 11  8  7 19 11 11  4]
20
[15 11  8]
[11 19  7  8 11 15 20  7]


In [57]:
import numpy as np

a = np.arange(1,6)
sum_a = np.sum(a)         # 합
print(sum_a)
mean_a = np.mean(a)       # 평균
print(mean_a)
median_a = np.median(a)   # 중앙값
print(median_a)
var_a = np.var(a)         # 모집단 분산
print(var_a)
std_a = np.std(a)         # 모집단 표준편차
print(std_a)

var_as = np.var(a, ddof=1)# 표본 분산
print(var_as)
std_as = np.std(a, ddof=1)# 표본 표준편차
print(std_as)

15
3.0
3.0
2.0
1.4142135623730951
2.5
1.5811388300841898


In [62]:
# 빈 칸을 정의하는 방법 1  Nan = Not a Number : np.nan ( 결측치, missing value)
import numpy as np

a = np.array([2,34,np.nan,23,309])
print(a)
print(np.mean(a))     # nan 값이 있으면 평균이 구해지지 않음 -> 분산, 표준편차 다 안됨
print(np.nanmean(a))  # nan 값을 제외하고 평균을 구해주는 함수, nan을 완전히 배제하고 연산함. (2+34+23+3009)/4

a_filtered = a[~np.isnan(a)]
print(a_filtered)

# nan과 none 값 비교
value = np.nan
if(np.isnan(value)):
  print('값이 Nan입니다')
print(value + 1)

[  2.  34.  nan  23. 309.]
nan
92.0
[  2.  34.  23. 309.]
값이 Nan입니다
nan


In [73]:
# 벡터 합치기
import numpy as np

str_vec = np.array(['사과', '배', '수박','참외'])
print(str_vec)
# 자동으로 통일할 수 있는 자료형으로 변환 후 벡터로 저장
mix_arr = np.array(['사과', 12, '수박','참외'])   # 정수형 12를 문자열로 바꿔서 벡터로 저장
print(mix_arr)

# 같은 행으로 쭉 이어서 붙임
combined_vec = np.concatenate([str_vec, mix_arr])
print(combined_vec)

# 열로 세워서 stack함
col_stacked = np.column_stack([np.arange(1,5),np.arange(12,16)])
print(col_stacked)

# 행으로 길게 세워서 stack처럼 쌓음
#row_stacked = np.row_stack([np.arange(1,5), np.arange(12,16)])
# Warning  `row_stack` alias is deprecated. Use `np.vstack` directly
row_stacked = np.vstack([np.arange(1,5), np.arange(12,16)])
print(row_stacked)

# stack을 하려면 두 배열의 갯수가 맞아야 함.
# 두 배열의 갯수가 다를 시. 에러가 발생 (아래와같이)
#unevan_stacked = np.column_stack([np.arange(1,5), np.arange(12,18)])
print(unevan_stacked)

# np.resize(원본 np, 해당 배열을 바꾸고 싶은 길이값)  반환값: 원본 np를 바꾸고 싶은 길이값만큼 늘리거나 줄인 값.
# 늘려야 할 땐, 아무런 매개변수가 없다면 원본 np가 처음부터 다시 반복된다
# 두 배열의 길이가 다를 때. 붙이는 법
vec1 = np.arange(1,5)
vec2 = np.arange(1,18)
vec1 = np.resize(vec1, len(vec2))
print(vec1)
unevan_stacked = np.column_stack([vec1, vec2])
print(unevan_stacked)

['사과' '배' '수박' '참외']
['사과' '12' '수박' '참외']
['사과' '배' '수박' '참외' '사과' '12' '수박' '참외']
[[ 1 12]
 [ 2 13]
 [ 3 14]
 [ 4 15]]
[[ 1  2  3  4]
 [12 13 14 15]]
[[ 1 12]
 [ 2 13]
 [ 3 14]
 [ 4 15]]
[1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4 1]
[[ 1  1]
 [ 2  2]
 [ 3  3]
 [ 4  4]
 [ 1  5]
 [ 2  6]
 [ 3  7]
 [ 4  8]
 [ 1  9]
 [ 2 10]
 [ 3 11]
 [ 4 12]
 [ 1 13]
 [ 2 14]
 [ 3 15]
 [ 4 16]
 [ 1 17]]


In [77]:
# 행렬
import numpy as np

a = np.array([[1,2,3], [4,5,6]])  # 2차원 배열 (2행 3열)
print(a)
print(a.shape)  # 행렬의 크기

print(a.cumsum())        # 전체를 1차원으로 보고 누적 합 을 하나하나씩 알려줌
print(a.cumsum(axis=0))  # 열 기준 누적 합 을 하나하나 씩 알려줌
print(a.cumsum(axis=1))  # 행 기준 누적 합 을 하나하나 씩 알려줌


[[1 2 3]
 [4 5 6]]
(2, 3)
[ 1  3  6 10 15 21]
[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]


In [81]:
# pandas (Panel Data Analysis)
import pandas as pd

import numpy as np

matrix = np.array([['1','2','3','4','5'],[6,7,8,9,10]])
print(matrix)

# 데이터 프레임 (Data Frame)
# 데이터 프레임은 서로 다른 자료형 끼리 합쳐도 그냥 서로 다른채로 합쳐진다
df = pd.DataFrame({
    'col1':['one','two','three','four','five'],
    'col2':[6,7,8,9,10]
})

print(df)
print(df['col1'].dtype)   # 문자열이 아닌 '객체' 로 구분됨
print(df['col2'].dtype)   # 64비트의 정수로 구분

[['1' '2' '3' '4' '5']
 ['6' '7' '8' '9' '10']]
    col1  col2
0    one     6
1    two     7
2  three     8
3   four     9
4   five    10
object
int64


In [83]:
# 빈 데이터 프레임 만들기
import pandas as pd

# 딕셔너리로 만듬
my_df = pd.DataFrame({
    '실수' : pd.Series(dtype='float'),
    '정수' : pd.Series(dtype='int'),
    '범주형' : pd.Series(dtype='category'),
    '논리' : pd.Series(dtype='bool'),
    '문자열' : pd.Series(dtype='str'),
})
# pd.Series() : 판다스에서 제공하는 1차원을 만드는 함수, dtype= 옵션으로 판다스배열의 자료형을 지정
print(my_df)
print(my_df.dtypes)   # DataFrame에서 모든 행렬의 자료형을 확인하려면 .dtypes로 붙여야함

Empty DataFrame
Columns: [실수, 정수, 범주형, 논리, 문자열]
Index: []
실수      float64
정수        int64
범주형    category
논리         bool
문자열      object
dtype: object
